import:
  - ~/.alacritty-colorscheme/themes/hyper.yaml

font:
  normal:
    family: 3270 Nerd Font
    style: Regular

  bold:
    family: 3270 Nerd Font
    style: Bold

  italic:
    family: 3270 Nerd Font
    style: Italic

  bold_italic:
    family: 3270 Nerd Font
    style: Bold Italic

  size: 14

env:
  TERM: xterm-256color
  LANG: "en_US.UTF-8"
  LC_COLLATE: "en_US.UTF-8"
  LC_CTYPE: "UTF-8"
  LC_MESSAGES: "en_US.UTF-8"
  LC_MONETARY: "en_US.UTF-8"
  LC_NUMERIC: "en_US.UTF-8"
  LC_TIME: "en_US.UTF-8"

shell:
  program: /bin/zsh
  args:
    - --login

window:
  opacity: 0.8
