import:
  - ~/.alacritty-colorscheme/themes/Cobalt2.yaml

font:
  normal:
    family: 3270 Nerd Font
    style: Regular

  bold:
    family: 3270 Nerd Font
    style: Bold

  italic:
    family: 3270 Nerd Font
    style: Italic

  bold_italic:
    family: 3270 Nerd Font
    style: Bold Italic

  size: 14

env:
  TERM: xterm-256color

shell:
  program: /bin/zsh
  args:
    - --login

window:
  opacity: 0.8
