MapV("<leader>y", '"+y', "[Y]ank to system clipboard")
MapN("<leader>p", '"+p', "[P]aste from system clipboard")
MapN("<leader>H", ":nohlsearch<CR>", "clear search [H]ighlighting")
MapN("<leader><leader>b", "<cmd>Telescope buffers<CR>", "[B]uffers")
MapN("<leader>bn", "<cmd>bnext<CR>", "[B]uffer [N]ext")
MapN("<leader>bp", "<cmd>bprev<CR>", "[B]uffer [P]revious")
