# This is the 1Password SSH agent config file, which allows you to customize the
# behavior of the SSH agent running on this machine.
#
# You can use it to:
# * Enable keys from other vaults than the Private vault
# * Control the order in which keys are offered to SSH servers
#
# EXAMPLE
#
# By default, all keys in your Private vault(s) are enabled:
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can enable more keys by adding more `[[ssh-keys]]` entries.
# For example, to first enable item "My SSH Key" from "My Custom Vault":
#
#  [[ssh-keys]]
#  item = "My SSH Key"
#  vault = "My Custom Vault"
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can test the result by running:
#
#  SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l
#  SSH_AUTH_SOCK=~/.1password/agent.sock ssh-add -l
#
# More examples can be found here:
#  https://developer.1password.com/docs/ssh/agent/config
[[ssh-keys]]
vault = "Private"
item = "awsvm"

[[ssh-keys]]
vault = "Private"
item = "azvm"

[[ssh-keys]]
vault = "Private"
item = "GitHub 202308"

[[ssh-keys]]
vault = "Private"
item = "Azure DevOps 202406"

[[ssh-keys]]
vault = "Private"
item = "kwlinux"

[[ssh-keys]]
vault = "KSLN Shared"
